# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
    - GO111MODULE=on

before:
    hooks:
        # You may remove this if you don't use go modules.
        - go mod download
        # you may remove this if you don't need go generate
        - go generate ./...
        - ./bin/completion
        - ./bin/manpages
builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - "386"
          - amd64
          - arm
          - arm64
          - ppc64
      ignore:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: ppc64
          - goos: darwin
            goarch: "386"
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: ppc64
      mod_timestamp: "{{ .CommitTimestamp }}"
      ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=source
archives:
    - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      formats:
          - tar.gz
      format_overrides:
          - goos: windows
            formats:
                - zip

homebrew_casks:
    - repository:
          owner: tomba-io
          name: homebrew-tap
      homepage: https://tomba.io
      directory: Casks
      description: CLI utility to search or verify lists of email addresses in seconds.
      license: Apache-2.0
      binaries:
          - tomba

scoops:
    - repository:
          owner: tomba-io
          name: scoop-bucket
      homepage: https://tomba.io
      description: CLI utility to search or verify lists of email addresses in seconds.
      license: Apache-2.0

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"
nfpms:
    - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      homepage: https://tomba.io
      description: CLI utility to search or verify lists of email addresses in seconds.
      maintainer: Mohamed Ben rebia <b.mohamed@tomba.io>
      license: Apache-2.0
      vendor: Tomba
      section: utils
      formats:
          - apk
          - deb
          - rpm
          - archlinux
      dependencies:
          - git
          - systemd
      recommends:
          - golang
      bindir: /usr/bin
      contents:
          - src: ./res/package/system/tomba.service
            dst: /lib/systemd/system/tomba.service
          - src: ./res/package/completion/tomba.bash
            dst: /usr/share/bash-completion/completions/tomba
            file_info:
                mode: 0644
          - src: ./res/package/completion/tomba.fish
            dst: /usr/share/fish/vendor_completions.d/tomba.fish
            file_info:
                mode: 0644
          - src: ./res/package/completion/tomba.zsh
            dst: /usr/share/zsh/vendor-completions/_tomba
            file_info:
                mode: 0644
          - src: ./res/package/manpages/tomba.1.gz
            dst: /usr/share/man/man1/tomba.1.gz
            file_info:
                mode: 0644
          - src: ./LICENSE
            dst: /usr/share/doc/tomba/copyright
            file_info:
                mode: 0644
      scripts:
          postinstall: ./res/package/scripts/postinstall.sh
      rpm:
          signature:
              key_file: /tmp/signing-key.gpg
      deb:
          signature:
              key_file: /tmp/signing-key.gpg
              type: origin

snapcrafts:
    - name: tomba
      summary: CLI utility to search or verify lists of email addresses in seconds
      description: |
          Tomba.io (CLI) utility to search or verify lists of email addresses in seconds can significantly improve productivity and efficiency for individuals and businesses dealing with large email databases. This utility can automate the process of checking the validity and deliverability of email addresses, saving valuable time and resources.

          Features:
          * Instantly locate email addresses from any website (Domain Search)
          * Email verify to confirm an email address' authenticity
          * Enrich email with data
          * Instantly discover the email addresses of Linkedin URLs
          * Instantly discover the email addresses of article authors
          * Phone finder to get phone numbers associated with emails
          * Phone validator to verify phone number validity
          * Find similar websites and their email addresses
          * Technology lookup to discover technologies used by domains
          * Count email addresses available for any domain
      grade: stable
      confinement: strict
      license: Apache-2.0
      base: core24
      publish: true
      apps:
          tomba:
              command: tomba
              plugs:
                  - home
                  - network

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - Merge pull request
            - Merge branch
