name: tomba
icon: logo.png
summary: CLI utility to search or verify lists of email addresses in seconds
description: |
    Tomba.io (CLI) utility to search or verify lists of email addresses in seconds can significantly improve productivity and efficiency for individuals and businesses dealing with large email databases. This utility can automate the process of checking the validity and deliverability of email addresses, saving valuable time and resources. Let's explore the features and benefits of such a CLI utility:

    * Instantly locate email addresses from any website https://tomba.io/domain-search .
    * Email verify to confirm an email address' authenticity https://tomba.io/email-verifier . 
    * Enrich email with data https://tomba.io/enrichment .
    * Instantly discover the email addresses of Linkedin URLs https://tomba.io/linkedin-finder .
    * Instantly discover the email addresses of article authors https://tomba.io/author-finder .
    * Phone finder to get phone numbers associated with emails https://tomba.io/phone-finder .
    * Phone validator to verify phone number validity.
    * Find similar websites and their email addresses.
    * Technology lookup to discover technologies used by domains.
    * Count email addresses available for any domain.

    This snap is built via the build.snapcraft.io service from the snapcraft.yaml definition at https://github.com/tomba-io/tomba to ensure source and build transparency.
issues: https://github.com/tomba-io/tomba/issues
license: "Apache-2.0"
source-code: https://github.com/tomba-io/tomba.git
website: https://tomba.io/
version: 1.1.2
grade: stable
base: core24

confinement: strict

apps:
    tomba:
        command: bin/tomba
        plugs:
            - home
            - network

parts:
    tomba:
        plugin: go
        source-type: git
        source: https://github.com/tomba-io/tomba
        build-snaps:
            - go/latest/stable
